<?php
// Admin Fix Settings - Safe defaults and DB test
if (function_exists('ini_set')) { @ini_set('display_errors', '1'); }
@error_reporting(E_ALL);
if (session_status() !== PHP_SESSION_ACTIVE) { session_start(); }
$envLoader = __DIR__ . '/../config/env.php';
if (is_readable($envLoader)) { require_once $envLoader; }

$scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'localhost';
$baseUrl = $scheme . '://' . $host;

if (!defined('SITE_URL')) { define('SITE_URL', getenv('SITE_URL') ?: $baseUrl); }
if (!defined('SITE_NAME')) { define('SITE_NAME', getenv('SITE_NAME') ?: 'SMM Pro'); }

// Restrict to admins
if (!isset($_SESSION['admin_id'])) {
    header('Location: ' . rtrim(SITE_URL, '/') . '/admin/login.php');
    exit();
}

$messages = [];
$success = false;

// Defaults provided by user
$defaults = [
    'SITE_NAME' => SITE_NAME,
    'SITE_URL'  => rtrim(SITE_URL, '/'),
    'UPLOAD_DIR'=> 'uploads/',
    'LOGS_DIR'  => 'logs/',
    'DB_HOST'   => getenv('DB_HOST') ?: 'localhost',
    'DB_NAME'   => getenv('DB_NAME') ?: 'u634930929_Inoo',
    'DB_USER'   => getenv('DB_USER') ?: 'u634930929_Inoo',
    'DB_PASS'   => getenv('DB_PASS') ?: 'Ino1234@',
];

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Write config/local_settings.php with defaults
    $vars = $defaults;
    $php = "<?php\n// Generated by admin/fix_settings on ".date('c')."\n";
    foreach ($vars as $k => $v) {
        $escaped = var_export($v, true);
        $php .= "putenv('{$k}=' . {$escaped});\n";
        $php .= "\n// Also sync into \\$_ENV/\\$_SERVER\n";
        $php .= "\\$_ENV['{$k}'] = {$escaped};\n";
        $php .= "\\$_SERVER['{$k}'] = {$escaped};\n";
    }
    $target = __DIR__ . '/../config/local_settings.php';
    $dir = dirname($target);
    if (!is_dir($dir)) { @mkdir($dir, 0775, true); }
    if (@file_put_contents($target, $php) === false) {
        $messages[] = "❌ Impossible d'écrire config/local_settings.php (permissions)";
    } else {
        $messages[] = "✅ Paramètres enregistrés dans config/local_settings.php";
        $success = true;
    }

    // Ensure folders
    $uploads = __DIR__ . '/../' . $defaults['UPLOAD_DIR'];
    if (!is_dir($uploads)) {
        if (@mkdir($uploads, 0777, true)) { $messages[] = '✅ Dossier uploads créé'; }
        else { $messages[] = '❌ Impossible de créer uploads (permissions)'; }
    }
    $logs = __DIR__ . '/../' . $defaults['LOGS_DIR'];
    if (!is_dir($logs)) {
        if (@mkdir($logs, 0777, true)) { $messages[] = '✅ Dossier logs créé'; }
        else { $messages[] = '❌ Impossible de créer logs (permissions)'; }
    }

    // Test DB connection
    try {
        $pdo = new PDO(
            'mysql:host=' . $defaults['DB_HOST'] . ';dbname=' . $defaults['DB_NAME'] . ';charset=utf8mb4',
            $defaults['DB_USER'],
            $defaults['DB_PASS'],
            [ PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION ]
        );
        $ver = $pdo->query('SELECT VERSION() as v')->fetch(PDO::FETCH_ASSOC);
        $messages[] = '✅ Connexion DB OK — MySQL ' . ($ver['v'] ?? '');
    } catch (Throwable $e) {
        $messages[] = '❌ Connexion DB échouée: ' . $e->getMessage();
        $success = false;
    }
}
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fix Settings - Admin <?php echo htmlspecialchars(SITE_NAME); ?></title>
    <link rel="stylesheet" href="<?php echo rtrim(SITE_URL, '/'); ?>/assets/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <div class="nav-content">
                <a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/dashboard.php" class="logo">
                    <i class="fas fa-wrench"></i> Fix Settings
                </a>
                <ul class="nav-links">
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/diagnostics.php">Diagnostics</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/logout.php" class="btn btn-secondary">Déconnexion</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="dashboard">
        <div class="container">
            <div class="card" style="margin-bottom: 1.5rem;">
                <h2 style="color: var(--primary-color); margin-bottom: 1rem;"><i class="fas fa-sliders-h"></i> Paramètres proposés</h2>
                <div style="display:grid; gap:0.5rem; color: var(--text-secondary);">
                    <?php foreach ($defaults as $k => $v): ?>
                        <div><strong><?php echo htmlspecialchars($k); ?>:</strong> <span style="color: var(--text-primary);"><?php echo htmlspecialchars($v); ?></span></div>
                    <?php endforeach; ?>
                </div>
                <form method="POST" style="margin-top: 1rem;">
                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Appliquer et tester</button>
                    <a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/settings.php" class="btn btn-secondary">Aller aux Settings</a>
                </form>
            </div>

            <?php if (!empty($messages)): ?>
            <div class="card">
                <h3 style="color: var(--primary-color); margin-bottom: 1rem;"><i class="fas fa-list"></i> Résultats</h3>
                <div style="display:grid; gap:0.5rem;">
                    <?php foreach ($messages as $m): ?>
                        <div style="padding:0.75rem; border:1px solid var(--border-color); border-radius:8px; background: var(--secondary-color);">
                            <?php echo htmlspecialchars($m); ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php endif; ?>
        </div>
    </div>
</body>
</html>