<?php
// Decoupled bootstrap without requiring database.php
if (session_status() !== PHP_SESSION_ACTIVE) { session_start(); }
// Load .env if available
$envLoader = __DIR__ . '/../config/env.php';
if (is_readable($envLoader)) { require_once $envLoader; }

// Derive base URL from request if SITE_URL not set
$scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
$host = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'localhost';
$derivedBase = $scheme . '://' . $host;

if (!defined('SITE_URL')) { define('SITE_URL', getenv('SITE_URL') ?: $derivedBase); }
if (!defined('SITE_NAME')) { define('SITE_NAME', getenv('SITE_NAME') ?: 'SMM Pro'); }
if (!defined('UPLOAD_DIR')) { define('UPLOAD_DIR', rtrim(getenv('UPLOAD_DIR') ?: 'uploads/', '/') . '/'); }
if (!defined('LOGS_DIR')) { define('LOGS_DIR', rtrim(getenv('LOGS_DIR') ?: 'logs/', '/') . '/'); }

// Ensure only admins can access
if (!isset($_SESSION['admin_id'])) {
    $base = rtrim(SITE_URL, '/');
    header('Location: ' . $base . '/admin/login.php');
    exit();
}

// Current values
$current = [
    'SITE_NAME' => SITE_NAME,
    'SITE_URL' => SITE_URL,
    'UPLOAD_DIR' => UPLOAD_DIR,
    'LOGS_DIR' => LOGS_DIR,
];

// Mail current
$mailCurrent = [
    'MAIL_FROM_EMAIL' => getenv('MAIL_FROM_EMAIL') ?: '',
    'MAIL_FROM_NAME' => getenv('MAIL_FROM_NAME') ?: '',
    'MAIL_BCC' => getenv('MAIL_BCC') ?: '',
    'MAIL_RETURN_PATH' => getenv('MAIL_RETURN_PATH') ?: '',
];

// DB current (from environment)
$dbCurrent = [
    'DB_HOST' => getenv('DB_HOST') ?: '',
    'DB_NAME' => getenv('DB_NAME') ?: '',
    'DB_USER' => getenv('DB_USER') ?: '',
    'DB_PASS' => getenv('DB_PASS') ?: '',
];

$success = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $siteName = trim(isset($_POST['SITE_NAME']) ? $_POST['SITE_NAME'] : '');
    $siteUrl = trim(isset($_POST['SITE_URL']) ? $_POST['SITE_URL'] : '');
    $uploadDir = trim(isset($_POST['UPLOAD_DIR']) ? $_POST['UPLOAD_DIR'] : '');
    $logsDir = trim(isset($_POST['LOGS_DIR']) ? $_POST['LOGS_DIR'] : '');

    if ($siteName === '' || $siteUrl === '' || $uploadDir === '' || $logsDir === '') {
        $error = "Tous les champs sont obligatoires.";
    } else {
        if ($uploadDir !== '' && substr($uploadDir, -1) !== '/') { $uploadDir .= '/'; }
        if ($logsDir !== '' && substr($logsDir, -1) !== '/') { $logsDir .= '/'; }

        $vars = [
            'SITE_NAME' => $siteName,
            'SITE_URL' => $siteUrl,
            'UPLOAD_DIR' => $uploadDir,
            'LOGS_DIR' => $logsDir,
            // DB vars (optionnel)
            'DB_HOST' => trim(isset($_POST['DB_HOST']) ? $_POST['DB_HOST'] : ($dbCurrent['DB_HOST'] ?? '')),
            'DB_NAME' => trim(isset($_POST['DB_NAME']) ? $_POST['DB_NAME'] : ($dbCurrent['DB_NAME'] ?? '')),
            'DB_USER' => trim(isset($_POST['DB_USER']) ? $_POST['DB_USER'] : ($dbCurrent['DB_USER'] ?? '')),
            'DB_PASS' => trim(isset($_POST['DB_PASS']) ? $_POST['DB_PASS'] : ($dbCurrent['DB_PASS'] ?? '')),
            // Mail vars
            'MAIL_FROM_EMAIL' => trim(isset($_POST['MAIL_FROM_EMAIL']) ? $_POST['MAIL_FROM_EMAIL'] : ($mailCurrent['MAIL_FROM_EMAIL'] ?? '')),
            'MAIL_FROM_NAME' => trim(isset($_POST['MAIL_FROM_NAME']) ? $_POST['MAIL_FROM_NAME'] : ($mailCurrent['MAIL_FROM_NAME'] ?? '')),
            'MAIL_BCC' => trim(isset($_POST['MAIL_BCC']) ? $_POST['MAIL_BCC'] : ($mailCurrent['MAIL_BCC'] ?? '')),
            'MAIL_RETURN_PATH' => trim(isset($_POST['MAIL_RETURN_PATH']) ? $_POST['MAIL_RETURN_PATH'] : ($mailCurrent['MAIL_RETURN_PATH'] ?? '')),
        ];
        $php = "<?php\n// Generated by admin/settings on ".date('c')."\n";
        foreach ($vars as $k => $v) {
            $escaped = var_export($v, true);
            $php .= "putenv('{$k}=' . {$escaped});\n";
            $php .= "\n// Also sync into \\$_ENV/\\$_SERVER\n";
            $php .= "\\$_ENV['{$k}'] = {$escaped};\n";
            $php .= "\\$_SERVER['{$k}'] = {$escaped};\n";
        }

        $target = __DIR__ . '/../config/local_settings.php';
        $targetDir = dirname($target);
        if (!is_dir($targetDir)) { @mkdir($targetDir, 0775, true); }

        if (@file_put_contents($target, $php) === false) {
            $error = "Impossible d'enregistrer les paramètres (vérifiez les permissions du dossier config/).";
        } else {
            $success = 'Paramètres enregistrés avec succès.';
            $current['SITE_NAME'] = $siteName;
            $current['SITE_URL'] = $siteUrl;
            $current['UPLOAD_DIR'] = $uploadDir;
            $current['LOGS_DIR'] = $logsDir;
            // Update DB current
            $dbCurrent['DB_HOST'] = $vars['DB_HOST'];
            $dbCurrent['DB_NAME'] = $vars['DB_NAME'];
            $dbCurrent['DB_USER'] = $vars['DB_USER'];
            $dbCurrent['DB_PASS'] = $vars['DB_PASS'];
            // Update Mail current
            $mailCurrent['MAIL_FROM_EMAIL'] = $vars['MAIL_FROM_EMAIL'];
            $mailCurrent['MAIL_FROM_NAME'] = $vars['MAIL_FROM_NAME'];
            $mailCurrent['MAIL_BCC'] = $vars['MAIL_BCC'];
            $mailCurrent['MAIL_RETURN_PATH'] = $vars['MAIL_RETURN_PATH'];
        }
    }
}
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Paramètres du site - Admin <?php echo htmlspecialchars($current['SITE_NAME']); ?></title>
    <link rel="stylesheet" href="<?php echo rtrim(SITE_URL, '/'); ?>/assets/css/style.css">
    <link rel="stylesheet" href="<?php echo rtrim(SITE_URL, '/'); ?>/assets/css/admin-settings.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <div class="nav-content">
                <a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/dashboard.php" class="logo">
                    <i class="fas fa-shield-alt"></i>
                    <?php echo htmlspecialchars($current['SITE_NAME']); ?> - Admin
                </a>
                <ul class="nav-links">
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/dashboard.php">Dashboard</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/orders.php">Commandes</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/users.php">Utilisateurs</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/services.php">Services</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/categories.php">Catégories</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/logout.php" class="btn btn-secondary">Déconnexion</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="settings-container">
        <div class="container">
            <div class="settings-grid">
                <div>
                    <div class="settings-card">
                        <h2 style="color: var(--primary-color); margin-bottom: 1rem;"><i class="fas fa-sliders-h"></i> Paramètres du site</h2>
                        <?php if ($error): ?>
                            <div class="alert alert-error"><i class="fas fa-exclamation-circle"></i> <?php echo $error; ?></div>
                        <?php endif; ?>
                        <?php if ($success): ?>
                            <div class="alert alert-success"><i class="fas fa-check-circle"></i> <?php echo $success; ?></div>
                        <?php endif; ?>

                        <form method="POST" class="settings-form">
                            <div class="form-group">
                                <label for="SITE_NAME"><i class="fas fa-tag"></i> Nom du site</label>
                                <input type="text" id="SITE_NAME" name="SITE_NAME" class="form-control" required value="<?php echo htmlspecialchars($current['SITE_NAME']); ?>">
                            </div>
                            <div class="form-group">
                                <label for="SITE_URL"><i class="fas fa-link"></i> URL du site</label>
                                <input type="url" id="SITE_URL" name="SITE_URL" class="form-control" required placeholder="https://votre-domaine.com" value="<?php echo htmlspecialchars($current['SITE_URL']); ?>">
                            </div>
                            <div class="form-group">
                                <label for="UPLOAD_DIR"><i class="fas fa-folder-open"></i> Dossier/URL des uploads</label>
                                <input type="text" id="UPLOAD_DIR" name="UPLOAD_DIR" class="form-control" required placeholder="uploads ou /uploads ou https://cdn..." value="<?php echo htmlspecialchars($current['UPLOAD_DIR']); ?>">
                                <small style="color: var(--text-secondary);">Relatif (uploads), absolu (/uploads) ou URL complète.</small>
                            </div>
                            <div class="form-group">
                                <label for="LOGS_DIR"><i class="fas fa-file-alt"></i> Dossier des logs</label>
                                <input type="text" id="LOGS_DIR" name="LOGS_DIR" class="form-control" required placeholder="logs" value="<?php echo htmlspecialchars($current['LOGS_DIR']); ?>">
                            </div>

                            <hr style="border:none; height:1px; background: var(--border-color); margin:1rem 0;">
                        <h3 style="color: var(--primary-color); margin: 0 0 1rem 0;"><i class="fas fa-database"></i> Base de données (optionnel)</h3>
                        <div class="form-group">
                            <label for="DB_HOST"><i class="fas fa-server"></i> Hôte (DB_HOST)</label>
                            <input type="text" id="DB_HOST" name="DB_HOST" class="form-control" placeholder="localhost" value="<?php echo htmlspecialchars($dbCurrent['DB_HOST']); ?>">
                        </div>
                        <div class="form-group">
                            <label for="DB_NAME"><i class="fas fa-database"></i> Nom (DB_NAME)</label>
                            <input type="text" id="DB_NAME" name="DB_NAME" class="form-control" value="<?php echo htmlspecialchars($dbCurrent['DB_NAME']); ?>">
                        </div>
                        <div class="form-group">
                            <label for="DB_USER"><i class="fas fa-user"></i> Utilisateur (DB_USER)</label>
                            <input type="text" id="DB_USER" name="DB_USER" class="form-control" value="<?php echo htmlspecialchars($dbCurrent['DB_USER']); ?>">
                        </div>
                        <div class="form-group">
                            <label for="DB_PASS"><i class="fas fa-key"></i> Mot de passe (DB_PASS)</label>
                            <input type="password" id="DB_PASS" name="DB_PASS" class="form-control" value="<?php echo htmlspecialchars($dbCurrent['DB_PASS']); ?>">
                        </div>

                        <hr style="border:none; height:1px; background: var(--border-color); margin:1rem 0;">
                        <h3 style="color: var(--primary-color); margin: 0 0 1rem 0;"><i class="fas fa-envelope"></i> E‑mail (optionnel)</h3>
                        <div class="form-group">
                            <label for="MAIL_FROM_EMAIL"><i class="fas fa-at"></i> Expéditeur (MAIL_FROM_EMAIL)</label>
                            <input type="email" id="MAIL_FROM_EMAIL" name="MAIL_FROM_EMAIL" class="form-control" placeholder="no-reply@votre-domaine" value="<?php echo htmlspecialchars($mailCurrent['MAIL_FROM_EMAIL']); ?>">
                        </div>
                        <div class="form-group">
                            <label for="MAIL_FROM_NAME"><i class="fas fa-signature"></i> Nom expéditeur (MAIL_FROM_NAME)</label>
                            <input type="text" id="MAIL_FROM_NAME" name="MAIL_FROM_NAME" class="form-control" placeholder="Nom du site" value="<?php echo htmlspecialchars($mailCurrent['MAIL_FROM_NAME']); ?>">
                        </div>
                        <div class="form-group">
                            <label for="MAIL_BCC"><i class="fas fa-eye-slash"></i> Copie cachée BCC (MAIL_BCC)</label>
                            <input type="text" id="MAIL_BCC" name="MAIL_BCC" class="form-control" placeholder="ops@votre-domaine (optionnel)" value="<?php echo htmlspecialchars($mailCurrent['MAIL_BCC']); ?>">
                        </div>
                        <div class="form-group">
                            <label for="MAIL_RETURN_PATH"><i class="fas fa-undo"></i> Adresse de retour (MAIL_RETURN_PATH)</label>
                            <input type="text" id="MAIL_RETURN_PATH" name="MAIL_RETURN_PATH" class="form-control" placeholder="bounce@votre-domaine (optionnel)" value="<?php echo htmlspecialchars($mailCurrent['MAIL_RETURN_PATH']); ?>">
                        </div>

                        <div class="settings-actions">
                            <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Enregistrer</button>
                            <a class="btn btn-secondary" href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/dashboard.php"><i class="fas fa-arrow-left"></i> Retour</a>
                        </div>
                        </form>
                    </div>
                </div>

                <div>
                    <div class="settings-card">
                        <h3 style="color: var(--primary-color); margin-bottom: 1rem;"><i class="fas fa-info-circle"></i> Conseils</h3>
                        <ul style="color: var(--text-secondary); line-height:1.8; margin:0; padding-left:1.2rem;">
                            <li>Après modification de SITE_URL, reconnectez-vous si nécessaire.</li>
                            <li>Pour les images des preuves, vous pouvez définir UPLOAD_DIR en URL complète (ex: https://cdn.votre-site.com/uploads).</li>
                            <li>Assurez-vous que le dossier config/ est inscriptible pour sauvegarder les réglages.</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>