<?php
require_once __DIR__ . '/../includes/auth.php';
// Enable error display for this admin page only
if (function_exists('ini_set')) { @ini_set('display_errors', '1'); }
@error_reporting(E_ALL);
$auth = new Auth();
$auth->requireAdminLogin();

$admin = $auth->getCurrentAdmin();

// Current values
$current = [
    'SITE_NAME' => SITE_NAME,
    'SITE_URL' => SITE_URL,
    'UPLOAD_DIR' => UPLOAD_DIR,
    'LOGS_DIR' => defined('LOGS_DIR') ? LOGS_DIR : 'logs/',
];

$success = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $siteName = trim($_POST['SITE_NAME'] ?? '');
    $siteUrl = trim($_POST['SITE_URL'] ?? '');
    $uploadDir = trim($_POST['UPLOAD_DIR'] ?? '');
    $logsDir = trim($_POST['LOGS_DIR'] ?? '');

    if ($siteName === '' || $siteUrl === '' || $uploadDir === '' || $logsDir === '') {
        $error = "Tous les champs sont obligatoires.";
    } else {
        // Normalize directories with trailing slash
        if ($uploadDir !== '' && substr($uploadDir, -1) !== '/') { $uploadDir .= '/'; }
        if ($logsDir !== '' && substr($logsDir, -1) !== '/') { $logsDir .= '/'; }

        // Build local settings PHP
        $vars = [
            'SITE_NAME' => $siteName,
            'SITE_URL' => $siteUrl,
            'UPLOAD_DIR' => $uploadDir,
            'LOGS_DIR' => $logsDir,
        ];
        $php = "<?php\n// Generated by admin/settings on ".date('c')."\n";
        foreach ($vars as $k => $v) {
            $escaped = var_export($v, true);
            $php .= "putenv('{$k}=' . {$escaped});\n";
            $php .= "\n// Also sync into \\$_ENV/\\$_SERVER\n";
            $php .= "\\$_ENV['{$k}'] = {$escaped};\n";
            $php .= "\\$_SERVER['{$k}'] = {$escaped};\n";
        }

        $target = __DIR__ . '/../config/local_settings.php';
        $targetDir = dirname($target);
        if (!is_dir($targetDir)) {
            @mkdir($targetDir, 0775, true);
        }

        $bytes = @file_put_contents($target, $php);
        if ($bytes === false) {
            $error = "Impossible d'enregistrer les paramètres (permissions insuffisantes sur le dossier config/).";
        } else {
            $success = 'Paramètres mis à jour avec succès.';
            // Update in-memory values for immediate reflect
            $current['SITE_NAME'] = $siteName;
            $current['SITE_URL'] = $siteUrl;
            $current['UPLOAD_DIR'] = $uploadDir;
            $current['LOGS_DIR'] = $logsDir;
        }
    }
}
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Paramètres du site - Admin <?php echo htmlspecialchars($current['SITE_NAME']); ?></title>
    <link rel="stylesheet" href="../assets/css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <div class="nav-content">
                <a href="dashboard.php" class="logo">
                    <i class="fas fa-shield-alt"></i>
                    <?php echo htmlspecialchars($current['SITE_NAME']); ?> - Admin
                </a>
                <ul class="nav-links">
                    <li><a href="dashboard.php">Dashboard</a></li>
                    <li><a href="orders.php">Commandes</a></li>
                    <li><a href="users.php">Utilisateurs</a></li>
                    <li><a href="services.php">Services</a></li>
                    <li><a href="categories.php">Catégories</a></li>
                    <li><a href="settings.php" class="btn btn-primary">Paramètres</a></li>
                    <li><a href="../logout.php" class="btn btn-secondary">Déconnexion</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="dashboard">
        <div class="container">
            <div class="dashboard-header">
                <div>
                    <h1 style="color: var(--text-primary); margin-bottom: 0.5rem;">
                        <i class="fas fa-sliders-h"></i> Paramètres du site
                    </h1>
                    <p style="color: var(--text-secondary);">Gérez les informations principales de votre site.</p>
                </div>
            </div>

            <?php if ($error): ?>
                <div class="alert alert-error"><i class="fas fa-exclamation-circle"></i> <?php echo $error; ?></div>
            <?php endif; ?>
            <?php if ($success): ?>
                <div class="alert alert-success"><i class="fas fa-check-circle"></i> <?php echo $success; ?></div>
            <?php endif; ?>

            <div class="card">
                <form method="POST">
                    <div class="form-group">
                        <label for="SITE_NAME"><i class="fas fa-tag"></i> Nom du site</label>
                        <input type="text" id="SITE_NAME" name="SITE_NAME" class="form-control" required value="<?php echo htmlspecialchars($current['SITE_NAME']); ?>">
                    </div>
                    <div class="form-group">
                        <label for="SITE_URL"><i class="fas fa-link"></i> URL du site</label>
                        <input type="url" id="SITE_URL" name="SITE_URL" class="form-control" required placeholder="https://votre-domaine.com" value="<?php echo htmlspecialchars($current['SITE_URL']); ?>">
                    </div>
                    <div class="form-group">
                        <label for="UPLOAD_DIR"><i class="fas fa-folder-open"></i> Dossier/URL des uploads</label>
                        <input type="text" id="UPLOAD_DIR" name="UPLOAD_DIR" class="form-control" required placeholder="uploads ou /uploads ou https://cdn..." value="<?php echo htmlspecialchars($current['UPLOAD_DIR']); ?>">
                        <small style="color: var(--text-secondary);">Accepte un dossier relatif (uploads), un chemin absolu (/uploads) ou une URL complète.</small>
                    </div>
                    <div class="form-group">
                        <label for="LOGS_DIR"><i class="fas fa-file-alt"></i> Dossier des logs</label>
                        <input type="text" id="LOGS_DIR" name="LOGS_DIR" class="form-control" required placeholder="logs" value="<?php echo htmlspecialchars($current['LOGS_DIR']); ?>">
                    </div>

                    <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Enregistrer</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>