<?php
// Lightweight bootstrap (no DB requirement to render)
require_once __DIR__ . '/../config/database.php';
if (session_status() !== PHP_SESSION_ACTIVE) { session_start(); }

// Ensure only admins can access
if (!isset($_SESSION['admin_id'])) {
    $base = rtrim(SITE_URL, '/');
    header('Location: ' . $base . '/admin/login.php');
    exit();
}

// Current values from constants/env
$current = [
    'SITE_NAME' => SITE_NAME,
    'SITE_URL' => SITE_URL,
    'UPLOAD_DIR' => UPLOAD_DIR,
    'LOGS_DIR' => defined('LOGS_DIR') ? LOGS_DIR : 'logs/',
];

$success = '';
$error = '';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $siteName = trim(isset($_POST['SITE_NAME']) ? $_POST['SITE_NAME'] : '');
    $siteUrl = trim(isset($_POST['SITE_URL']) ? $_POST['SITE_URL'] : '');
    $uploadDir = trim(isset($_POST['UPLOAD_DIR']) ? $_POST['UPLOAD_DIR'] : '');
    $logsDir = trim(isset($_POST['LOGS_DIR']) ? $_POST['LOGS_DIR'] : '');

    if ($siteName === '' || $siteUrl === '' || $uploadDir === '' || $logsDir === '') {
        $error = "Tous les champs sont obligatoires.";
    } else {
        // Normalize directories with trailing slash
        if ($uploadDir !== '' && substr($uploadDir, -1) !== '/') { $uploadDir .= '/'; }
        if ($logsDir !== '' && substr($logsDir, -1) !== '/') { $logsDir .= '/'; }

        // Build local settings PHP overrides (idempotent)
        $vars = [
            'SITE_NAME' => $siteName,
            'SITE_URL' => $siteUrl,
            'UPLOAD_DIR' => $uploadDir,
            'LOGS_DIR' => $logsDir,
        ];
        $php = "<?php\n// Generated by admin/settings on ".date('c')."\n";
        foreach ($vars as $k => $v) {
            $escaped = var_export($v, true);
            $php .= "putenv('{$k}=' . {$escaped});\n";
            $php .= "\n// Also sync into \\$_ENV/\\$_SERVER\n";
            $php .= "\\$_ENV['{$k}'] = {$escaped};\n";
            $php .= "\\$_SERVER['{$k}'] = {$escaped};\n";
        }

        $target = __DIR__ . '/../config/local_settings.php';
        $targetDir = dirname($target);
        if (!is_dir($targetDir)) { @mkdir($targetDir, 0775, true); }

        if (@file_put_contents($target, $php) === false) {
            $error = "Impossible d'enregistrer les paramètres (vérifiez les permissions du dossier config/).";
        } else {
            $success = 'Paramètres enregistrés avec succès.';
            // Reflect immediately on page
            $current['SITE_NAME'] = $siteName;
            $current['SITE_URL'] = $siteUrl;
            $current['UPLOAD_DIR'] = $uploadDir;
            $current['LOGS_DIR'] = $logsDir;
        }
    }
}
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Paramètres du site - Admin <?php echo htmlspecialchars($current['SITE_NAME']); ?></title>
    <link rel="stylesheet" href="<?php echo rtrim(SITE_URL, '/'); ?>/assets/css/style.css">
    <link rel="stylesheet" href="<?php echo rtrim(SITE_URL, '/'); ?>/assets/css/admin-settings.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
    <nav class="navbar">
        <div class="container">
            <div class="nav-content">
                <a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/dashboard.php" class="logo">
                    <i class="fas fa-shield-alt"></i>
                    <?php echo htmlspecialchars($current['SITE_NAME']); ?> - Admin
                </a>
                <ul class="nav-links">
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/dashboard.php">Dashboard</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/orders.php">Commandes</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/users.php">Utilisateurs</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/services.php">Services</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/categories.php">Catégories</a></li>
                    <li><a href="<?php echo rtrim(SITE_URL, '/'); ?>/logout.php" class="btn btn-secondary">Déconnexion</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="settings-container">
        <div class="container">
            <div class="settings-grid">
                <div>
                    <div class="settings-card">
                        <h2 style="color: var(--primary-color); margin-bottom: 1rem;"><i class="fas fa-sliders-h"></i> Paramètres du site</h2>
                        <?php if ($error): ?>
                            <div class="alert alert-error"><i class="fas fa-exclamation-circle"></i> <?php echo $error; ?></div>
                        <?php endif; ?>
                        <?php if ($success): ?>
                            <div class="alert alert-success"><i class="fas fa-check-circle"></i> <?php echo $success; ?></div>
                        <?php endif; ?>

                        <form method="POST" class="settings-form">
                            <div class="form-group">
                                <label for="SITE_NAME"><i class="fas fa-tag"></i> Nom du site</label>
                                <input type="text" id="SITE_NAME" name="SITE_NAME" class="form-control" required value="<?php echo htmlspecialchars($current['SITE_NAME']); ?>">
                            </div>
                            <div class="form-group">
                                <label for="SITE_URL"><i class="fas fa-link"></i> URL du site</label>
                                <input type="url" id="SITE_URL" name="SITE_URL" class="form-control" required placeholder="https://votre-domaine.com" value="<?php echo htmlspecialchars($current['SITE_URL']); ?>">
                            </div>
                            <div class="form-group">
                                <label for="UPLOAD_DIR"><i class="fas fa-folder-open"></i> Dossier/URL des uploads</label>
                                <input type="text" id="UPLOAD_DIR" name="UPLOAD_DIR" class="form-control" required placeholder="uploads ou /uploads ou https://cdn..." value="<?php echo htmlspecialchars($current['UPLOAD_DIR']); ?>">
                                <small style="color: var(--text-secondary);">Relatif (uploads), absolu (/uploads) ou URL complète.</small>
                            </div>
                            <div class="form-group">
                                <label for="LOGS_DIR"><i class="fas fa-file-alt"></i> Dossier des logs</label>
                                <input type="text" id="LOGS_DIR" name="LOGS_DIR" class="form-control" required placeholder="logs" value="<?php echo htmlspecialchars($current['LOGS_DIR']); ?>">
                            </div>

                            <div class="settings-actions">
                                <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> Enregistrer</button>
                                <a class="btn btn-secondary" href="<?php echo rtrim(SITE_URL, '/'); ?>/admin/dashboard.php"><i class="fas fa-arrow-left"></i> Retour</a>
                            </div>
                        </form>
                    </div>
                </div>

                <div>
                    <div class="settings-card">
                        <h3 style="color: var(--primary-color); margin-bottom: 1rem;"><i class="fas fa-info-circle"></i> Conseils</h3>
                        <ul style="color: var(--text-secondary); line-height:1.8; margin:0; padding-left:1.2rem;">
                            <li>Après modification de SITE_URL, reconnectez-vous si nécessaire.</li>
                            <li>Pour les images des preuves, vous pouvez définir UPLOAD_DIR en URL complète (ex: https://cdn.votre-site.com/uploads).</li>
                            <li>Assurez-vous que le dossier config/ est inscriptible pour sauvegarder les réglages.</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>