<?php
// Minimal bootstrap
require_once __DIR__ . '/../../config/database.php';
if (session_status() !== PHP_SESSION_ACTIVE) { session_start(); }
header('Content-Type: application/json; charset=UTF-8');

if (!isset($_SESSION['admin_id'])) {
    http_response_code(401);
    echo json_encode(['success' => false, 'message' => 'Non autorisé']);
    exit;
}

$required = ['SITE_NAME','SITE_URL','UPLOAD_DIR','LOGS_DIR'];
foreach ($required as $k) {
    if (!isset($_POST[$k])) {
        http_response_code(400);
        echo json_encode(['success' => false, 'message' => 'Champs manquants']);
        exit;
    }
}

$siteName = trim($_POST['SITE_NAME']);
$siteUrl = trim($_POST['SITE_URL']);
$uploadDir = trim($_POST['UPLOAD_DIR']);
$logsDir = trim($_POST['LOGS_DIR']);

if ($siteName === '' || $siteUrl === '' || $uploadDir === '' || $logsDir === '') {
    http_response_code(400);
    echo json_encode(['success' => false, 'message' => 'Tous les champs sont obligatoires']);
    exit;
}

if ($uploadDir !== '' && substr($uploadDir, -1) !== '/') { $uploadDir .= '/'; }
if ($logsDir !== '' && substr($logsDir, -1) !== '/') { $logsDir .= '/'; }

$vars = [
    'SITE_NAME' => $siteName,
    'SITE_URL' => $siteUrl,
    'UPLOAD_DIR' => $uploadDir,
    'LOGS_DIR' => $logsDir,
];

$php = "<?php\n// Generated by admin/api/save_settings on ".date('c')."\n";
foreach ($vars as $k => $v) {
    $escaped = var_export($v, true);
    $php .= "putenv('{$k}=' . {$escaped});\n";
    $php .= "\n// Also sync into \\$_ENV/\\$_SERVER\n";
    $php .= "\\$_ENV['{$k}'] = {$escaped};\n";
    $php .= "\\$_SERVER['{$k}'] = {$escaped};\n";
}

$target = __DIR__ . '/../../config/local_settings.php';
$targetDir = dirname($target);
if (!is_dir($targetDir)) { @mkdir($targetDir, 0775, true); }

if (@file_put_contents($target, $php) === false) {
    http_response_code(500);
    echo json_encode(['success' => false, 'message' => "Impossible d'enregistrer les paramètres (permissions)"]);
    exit;
}

echo json_encode(['success' => true, 'message' => 'Paramètres enregistrés']);